# Generated by Django 2.1.7 on 2019-04-16 18:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('body', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, max_length=500)),
                ('img', models.URLField(blank=True)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('tokens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('topic_id', models.IntegerField(blank=True, null=True)),
                ('labeled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('most_recent_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsie.ArticleCluster'),
        ),
    ]
