# Generated by Django 2.1.5 on 2019-01-14 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=[], size=None),
        ),
    ]
