# Generated by Django 2.1.7 on 2019-04-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0002_auto_20190416_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecluster',
            name='size_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecluster',
            name='size_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecluster',
            name='size_today',
            field=models.IntegerField(default=0),
        ),
    ]
