# Generated by Django 2.1.7 on 2019-04-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0004_articlecluster_top_story_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic_id',
        ),
    ]
