# Generated by Django 2.1.7 on 2019-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0005_remove_article_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manual_label',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
