# Generated by Django 2.1.5 on 2019-02-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0005_auto_20190210_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tokens',
        ),
    ]
