# Generated by Django 2.1.5 on 2019-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0006_auto_20190213_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
