# Generated by Django 2.1.7 on 2019-05-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0006_article_manual_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsie.ArticleCluster'),
        ),
    ]
