# Generated by Django 2.1.5 on 2019-02-17 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0007_auto_20190217_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=[], size=None),
        ),
    ]
