# Generated by Django 2.1.7 on 2019-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0008_auto_20190506_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
