# Generated by Django 2.1.5 on 2019-03-05 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0010_auto_20190218_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
