# Generated by Django 2.1.5 on 2019-03-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0014_auto_20190306_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='top_story_number',
            new_name='top_story_id',
        ),
    ]
