# Generated by Django 2.1.5 on 2019-03-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0015_auto_20190306_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='top_story_id',
            new_name='story_id',
        ),
    ]
