# Generated by Django 2.1.5 on 2019-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0016_auto_20190309_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='labeled',
            field=models.BooleanField(default=False),
        ),
    ]
