# Generated by Django 2.1.5 on 2019-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0018_remove_article_labeled'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='labeled',
            field=models.BooleanField(default=True),
        ),
    ]
