# Generated by Django 2.1.5 on 2019-03-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsie', '0019_article_labeled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='story_id',
            new_name='topic_id',
        ),
    ]
